### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by safstromo** [chatgut/UserService#1]
Please update documentation with the default port used and what configs can be made :smile: 

Id also like to see coherent naming of the env variables for example rename DB_URL to MYSQL_URL or rename the user and pass to DB_

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/userService}
spring.datasource.username=${MYSQL_USER}
spring.datasource.password=${MYSQL_PASSWORD}

:heart:

**Comment by Lugn1** [comment]
Let me know if there's anything else
